/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "TNodeObserverProtocol-Protocol.h"

@interface TScriptableWindowController : NSWindowController <TNodeObserverProtocol>
{
    struct TNodeObserverCocoaBridge *_proxyNodeObserver;
    struct TFENode _proxyNode;
    struct CGRect _oldFrame;
}

+ (id)controllerForWindow:(id)arg1;
+ (void)initialize;
- (struct CGRect)finderScriptingContentRectForFrameRect:(const struct CGRect *)arg1;
- (struct CGRect)finderScriptingFrameRectForContentRect:(const struct CGRect *)arg1;
- (void)finderScriptingSetProperty:(unsigned int)arg1 value:(const struct AEDesc *)arg2 reply:(struct AEDesc *)arg3;
- (void)finderScriptingGetProperty:(unsigned int)arg1 requestedType:(const struct AEDesc *)arg2 desc:(struct AEDesc *)arg3;
- (unsigned int)finderScriptingModelKind;
- (void)windowDidEndMove:(id)arg1;
- (void)windowWillMove:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidEndLiveResize:(id)arg1;
- (BOOL)window:(id)arg1 shouldDragDocumentWithEvent:(id)arg2 from:(struct CGPoint)arg3 withPasteboard:(id)arg4;
- (BOOL)window:(id)arg1 shouldPopUpDocumentPathMenu:(id)arg2;
- (struct TFENode)fetchWindowProxyNode;
@property(readonly) struct TFENode target;
- (void)pathPopupSelect:(id)arg1;
- (void)pathPopupSelectedWithNode:(const struct TFENode *)arg1;
- (void)populatePathMenu:(id)arg1;
- (BOOL)shouldEnablePathMenuItem:(id)arg1 forNode:(const struct TFENode *)arg2;
- (id)windowIcon;
- (id)windowTitle;
- (void)updateWindowIcon;
- (void)updateWindowTitle;
- (void)configureWindowTitleAndIcon;
- (void)nodeChanged:(const struct TFENode *)arg1 inObservedNode:(const struct TFENode *)arg2 property:(unsigned int)arg3;
- (void)cmdClose:(id)arg1;
- (void)dealloc;
- (id)initWithWindow:(id)arg1;

@end

