/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@interface TViewController : NSViewController
{
    BOOL _callingLoadView;
    BOOL _loadingFromNib;
    BOOL _isViewLoaded;
}

@property(readonly) BOOL isViewLoaded; // @synthesize isViewLoaded=_isViewLoaded;
- (BOOL)applyExtraKeyboardShortcuts:(id)arg1;
- (NSView*)viewNoLoad;
- (void)viewLoaded;
- (void)setView:(NSView*)arg1;
- (void)loadView;
- (id)nibBundle;
- (void)awakeFromNib;
- (void)initCommon;
- (id)initWithCoder:(NSCoder*)arg1;
- (id)initWithNibName:(NSString*)arg1 bundle:(NSBundle*)arg2;
- (id)initWithNibName:(NSString*)arg1;

@end

